<?php

namespace app\admin\controller;

use think\Controller;

class Article extends Controller
{
    protected $db;
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->db=new \app\common\model\Article();
    }
    //首页
    public function index(){
        $field=db('article')->where('is_recycle',null)->whereOr('is_recycle',2)->select();
        //halt($field);能打印出来证明已经找到了表
        $this->assign('field',$field);//
        return $this->fetch();
    }
    //添加文章
    public function store(){
        if(request()->isPost()) {//j检测是否是post提交
            //halt(input('post.'));测处是否接受到用户提交过来的表单
            //如果是post提交请求model下的Admin模型
            $res = $this->db->store(input('post.'));
            if($res['valid']){
                $this->success($res['msg'],'store');exit;
            }else{
                $this->error($res['msg']);exit;
            }
        }
        return $this->fetch();
    }
    //编辑文章
    public function edit(){
        $arc_id=input('param.arc_id');
        //halt($arc_id);测试是否获得要编辑的编号
        //获取旧数据
        $oldDate=$this->db->find($arc_id);//获得编号为1的所有旧数据
        //halt($$oldDate);
        //把我们获得的所有旧数据分配到页面上,用assign
        $this->assign('oldDate',$oldDate);//
        //进入编辑方法
        if(request()->isPost()) {//j检测是否是post提交
            //halt(input('post.'));//测处是否接受到用户提交过来的表单
            //如果是post提交请求model下的Admin模型
            $res = $this->db->edit(input('post.'));
            if($res['valid']){
                //操作成功
                $this->success($res['msg'],'index');exit;
            }else{
                $this->error($res['msg']);exit;
            }
        }
        return $this->fetch();
    }
    /**
     * 提取回收站
     */
   public function recycle(){
    $field=db('article')->where('is_recycle',1)->select();
        //halt($field);能打印出来证明已经找到了表
        $this->assign('field',$field);//
        return $this->fetch();
   }
   /*删除到回收站*/
   public function delToRecycle(){
        
       $arc_id = input( 'param.arc_id' );
       $data=$this->db->save( [ 'is_recycle' => 1 ] , [ 'arc_id' => $arc_id ] ) ;
        //将该数据删除到回收站
        if ($data) {
            $this->success( '已经进入回收站' , 'index' );
            exit;
        }
        else {
            $this->error( '没有进入回收站' );
            exit;
        }
   }
  //从回收站中数据恢复
  public function outRecycle(){
     $arc_id = input( 'param.arc_id' );
       $data=$this->db->save( [ 'is_recycle' => 2 ] , [ 'arc_id' => $arc_id ] ) ;
        //将该数据删除到回收站
        if ($data) {
            $this->success( '已经将文章恢复' , 'index' );
            exit;
        }
        else {
            $this->error( '文章数据恢复没有成功' );
            exit;
        }
  }

   /**
     * 删除到回收站
     */
     public function  del(){
       //此处接受到页面上删除字段的id值
       $famlily_id=input('get.arc_id');//如果不是用框架，应使用param.famlily_id
       //halt($famlily_id);
       //下面请求模型中的del方法来删除,去模型中建立一个对应的模块del去进行删除
       $res=$this->db->del(input('get.arc_id'));
       if($res['valid']){
           $this->success($res['msg'],'index');exit;
       }else{
           $this->error($res['msg']);exit;
       }
   }
}
