<?php

namespace app\admin\controller;

use think\Controller;

class Book extends Controller
{
	protected $db;
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->db=new \app\common\model\Book();
    }
	public function book(){
		$field=db('moneybook')->select();
        //halt($field);能打印出来证明已经找到了表
        $this->assign('field',$field);//
        $field1=db('internet')->select();
        //halt($field);能打印出来证明已经找到了表
        $this->assign('field1',$field1);//
        $field2=db('up')->select();
        //halt($field);能打印出来证明已经找到了表
        $this->assign('field2',$field2);//
		return $this->fetch();
	}
	//跟新书目
	public function update(){
		$moneybook_id=input('param.moneybook_id');
        //halt($arc_id);测试是否获得要编辑的编号
        //获取旧数据
        $oldDate=db('moneybook')->where('moneybook_id',$moneybook_id)->find();//获得编号为1的所有旧数据
        //halt($$oldDate);
        //把我们获得的所有旧数据分配到页面上,用assign
        $this->assign('oldDate',$oldDate);//
         if(request()->isPost()) {//j检测是否是post提交
            //halt(input('post.'));//测处是否接受到用户提交过来的表单
            //如果是post提交请求model下的Admin模型
            $res = $this->db->edit(input('post.'));
            if($res['valid']){
                //操作成功
                $this->success($res['msg'],'book');exit;
            }else{
                $this->error($res['msg']);exit;
            }
        }
		return $this->fetch();
	}
	public function update1(){
		$internet_id=input('param.internet_id');
        //halt($arc_id);测试是否获得要编辑的编号
        //获取旧数据
        $oldDate=db('internet')->where('internet_id',$internet_id)->find();//获得编号为1的所有旧数据
        //halt($$oldDate);
        //把我们获得的所有旧数据分配到页面上,用assign
        $this->assign('oldDate',$oldDate);//
         if(request()->isPost()) {//j检测是否是post提交
            //halt(input('post.'));//测处是否接受到用户提交过来的表单
            //如果是post提交请求model下的Admin模型
            $res = $this->db->edit1(input('post.'));
            if($res['valid']){
                //操作成功
                $this->success($res['msg'],'book');exit;
            }else{
                $this->error($res['msg']);exit;
            }
        }
		return $this->fetch();
	}
    public function update2(){
        $up_id=input('param.up_id');
        //halt($arc_id);测试是否获得要编辑的编号
        //获取旧数据
        $oldDate=db('up')->where('up_id',$up_id)->find();//获得编号为1的所有旧数据
        //halt($$oldDate);
        //把我们获得的所有旧数据分配到页面上,用assign
        $this->assign('oldDate',$oldDate);//
         if(request()->isPost()) {//j检测是否是post提交
            //halt(input('post.'));//测处是否接受到用户提交过来的表单
            //如果是post提交请求model下的Admin模型
            $res = $this->db->edit2(input('post.'));
            if($res['valid']){
                //操作成功
                $this->success($res['msg'],'book');exit;
            }else{
                $this->error($res['msg']);exit;
            }
        }
        return $this->fetch();
    }
}