<?php

namespace app\admin\controller;

use think\Controller;

class Camera extends Controller
{
	protected $db;
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->db=new \app\common\model\Camera();
    }
	public function camera(){
		$field=db('photo')->select();
        //halt($field);能打印出来证明已经找到了表
        $this->assign('field',$field);//
		return $this->fetch();
	}
    public function add(){
        if(request()->isPost()) {//j检测是否是post提交
            //halt(input('post.'));测处是否接受到用户提交过来的表单
            //如果是post提交请求model下的Admin模型
            $res = $this->db->store(input('post.'));
            if($res['valid']){
                //操作成功
                $this->success($res['msg'],'camera');exit;
            }else{
                $this->error($res['msg']);exit;
            }
        }
        return $this->fetch();
    }
    public function del(){
    	   $photo_id=input('get.photo_id');//如果不是用框架，应使用param.famlily_id
       //halt($famlily_id);
       //下面请求模型中的del方法来删除,去模型中建立一个对应的模块del去进行删除
       $res=$this->db->del(input('get.photo_id'));
       if($res['valid']){
           $this->success($res['msg'],'camera');exit;
       }else{
           $this->error($res['msg']);exit;
       }
     }
    }
