<?php

namespace app\admin\controller;

use think\Controller;

class Eat extends Controller
{  
	protected $db;
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->db=new \app\common\model\Eat();
    }
	public function eat(){
		$field=db('breakfast')->select();
        //halt($field);能打印出来证明已经找到了表
        $this->assign('field',$field);//
        $field1=db('lunch')->select();
        //halt($field);能打印出来证明已经找到了表
        $this->assign('field1',$field1);//
        $field2=db('dinner')->select();
        //halt($field);能打印出来证明已经找到了表
        $this->assign('field2',$field2);//
		return $this->fetch();
	}
	//更改早餐菜单
	public function update(){
		 $arc_id=input('param.breakfast_id');
        //halt($arc_id);测试是否获得要编辑的编号
        //获取旧数据
        $oldDate=$this->db->find($arc_id);//获得编号为1的所有旧数据
        //halt($$oldDate);
        //把我们获得的所有旧数据分配到页面上,用assign
        $this->assign('oldDate',$oldDate);//
         if(request()->isPost()) {//j检测是否是post提交
            //halt(input('post.'));//测处是否接受到用户提交过来的表单
            //如果是post提交请求model下的Admin模型
            $res = $this->db->edit(input('post.'));
            if($res['valid']){
                //操作成功
                $this->success($res['msg'],'eat');exit;
            }else{
                $this->error($res['msg']);exit;
            }
        }
        return $this->fetch();
	}
    public function update1(){
        $arc_id=input('param.lunch_id');
        //halt($arc_id);//测试是否获得要编辑的编号
        //获取旧数据
        $oldDate=db('lunch')->where('lunch_id',$arc_id)->find();//获得编号为1的所有旧数据
        //把我们获得的所有旧数据分配到页面上,用assign
        $this->assign('oldDate',$oldDate);//
         if(request()->isPost()) {//j检测是否是post提交
            //halt(input('post.'));//测处是否接受到用户提交过来的表单
            //如果是post提交请求model下的Admin模型
            $res = $this->db->edit1(input('post.'));
            if($res['valid']){
                //操作成功
                $this->success($res['msg'],'eat');exit;
            }else{
                $this->error($res['msg']);exit;
            }
        }
        return $this->fetch();
    }
    public function update2(){
       $arc_id=input('param.dinner_id');
        //halt($arc_id);//测试是否获得要编辑的编号
        //获取旧数据
        $oldDate=db('dinner')->where('dinner_id',$arc_id)->find();//获得编号为1的所有旧数据
        //把我们获得的所有旧数据分配到页面上,用assign
        $this->assign('oldDate',$oldDate);//
        if(request()->isPost()) {//j检测是否是post提交
            //halt(input('post.'));//测处是否接受到用户提交过来的表单
            //如果是post提交请求model下的Admin模型
            $res = $this->db->edit2(input('post.'));
            if($res['valid']){
                //操作成功
                $this->success($res['msg'],'eat');exit;
            }else{
                $this->error($res['msg']);exit;
            }
        }
        return $this->fetch();
    }
}